
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button button10;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button_point;

	private global::Gtk.Button button9;

	private global::Gtk.Button button6;

	private global::Gtk.Button button8;

	private global::Gtk.Button button_divide;

	private global::Gtk.Button button_minus;

	private global::Gtk.Button button_multiply;

	private global::Gtk.Button button_plus;

	private global::Gtk.Button button7;

	private global::Gtk.Button button_CE;

	private global::Gtk.Button button_C;

	private global::Gtk.Button button_equal;

	private global::Gtk.Entry output;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button10 = new global::Gtk.Button();
		this.button10.WidthRequest = 105;
		this.button10.HeightRequest = 44;
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("0");
		this.fixed1.Add(this.button10);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button10]));
		w1.X = 20;
		w1.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 44;
		this.button1.HeightRequest = 44;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("_1");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w2.X = 20;
		w2.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 44;
		this.button2.HeightRequest = 44;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w3.X = 80;
		w3.Y = 278;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 44;
		this.button3.HeightRequest = 44;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w4.X = 136;
		w4.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 44;
		this.button4.HeightRequest = 44;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.fixed1.Add(this.button4);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
		w5.X = 21;
		w5.Y = 221;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 44;
		this.button5.HeightRequest = 44;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.fixed1.Add(this.button5);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
		w6.X = 81;
		w6.Y = 219;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_point = new global::Gtk.Button();
		this.button_point.WidthRequest = 44;
		this.button_point.HeightRequest = 44;
		this.button_point.CanFocus = true;
		this.button_point.Name = "button_point";
		this.button_point.UseUnderline = true;
		this.button_point.Label = global::Mono.Unix.Catalog.GetString(",");
		this.fixed1.Add(this.button_point);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_point]));
		w7.X = 136;
		w7.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button9 = new global::Gtk.Button();
		this.button9.WidthRequest = 44;
		this.button9.HeightRequest = 44;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.fixed1.Add(this.button9);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button9]));
		w8.X = 139;
		w8.Y = 166;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 44;
		this.button6.HeightRequest = 44;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.fixed1.Add(this.button6);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
		w9.X = 137;
		w9.Y = 218;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button();
		this.button8.WidthRequest = 44;
		this.button8.HeightRequest = 44;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.fixed1.Add(this.button8);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button8]));
		w10.X = 79;
		w10.Y = 167;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_divide = new global::Gtk.Button();
		this.button_divide.WidthRequest = 44;
		this.button_divide.HeightRequest = 44;
		this.button_divide.CanFocus = true;
		this.button_divide.Name = "button_divide";
		this.button_divide.UseUnderline = true;
		this.button_divide.Label = global::Mono.Unix.Catalog.GetString("/");
		this.fixed1.Add(this.button_divide);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_divide]));
		w11.X = 192;
		w11.Y = 166;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_minus = new global::Gtk.Button();
		this.button_minus.WidthRequest = 44;
		this.button_minus.HeightRequest = 44;
		this.button_minus.CanFocus = true;
		this.button_minus.Name = "button_minus";
		this.button_minus.UseUnderline = true;
		this.button_minus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button_minus);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_minus]));
		w12.X = 192;
		w12.Y = 276;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_multiply = new global::Gtk.Button();
		this.button_multiply.WidthRequest = 44;
		this.button_multiply.HeightRequest = 44;
		this.button_multiply.CanFocus = true;
		this.button_multiply.Name = "button_multiply";
		this.button_multiply.UseUnderline = true;
		this.button_multiply.Label = global::Mono.Unix.Catalog.GetString("*");
		this.fixed1.Add(this.button_multiply);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_multiply]));
		w13.X = 193;
		w13.Y = 219;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_plus = new global::Gtk.Button();
		this.button_plus.WidthRequest = 44;
		this.button_plus.HeightRequest = 44;
		this.button_plus.CanFocus = true;
		this.button_plus.Name = "button_plus";
		this.button_plus.UseUnderline = true;
		this.button_plus.Label = global::Mono.Unix.Catalog.GetString("+");
		this.fixed1.Add(this.button_plus);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_plus]));
		w14.X = 191;
		w14.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 44;
		this.button7.HeightRequest = 44;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.fixed1.Add(this.button7);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button7]));
		w15.X = 23;
		w15.Y = 168;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_CE = new global::Gtk.Button();
		this.button_CE.WidthRequest = 44;
		this.button_CE.HeightRequest = 44;
		this.button_CE.CanFocus = true;
		this.button_CE.Name = "button_CE";
		this.button_CE.UseUnderline = true;
		this.button_CE.Label = global::Mono.Unix.Catalog.GetString("CE");
		this.fixed1.Add(this.button_CE);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_CE]));
		w16.X = 245;
		w16.Y = 166;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_C = new global::Gtk.Button();
		this.button_C.WidthRequest = 44;
		this.button_C.HeightRequest = 44;
		this.button_C.CanFocus = true;
		this.button_C.Name = "button_C";
		this.button_C.UseUnderline = true;
		this.button_C.Label = global::Mono.Unix.Catalog.GetString("C");
		this.fixed1.Add(this.button_C);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_C]));
		w17.X = 244;
		w17.Y = 218;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button_equal = new global::Gtk.Button();
		this.button_equal.WidthRequest = 44;
		this.button_equal.HeightRequest = 96;
		this.button_equal.CanFocus = true;
		this.button_equal.Name = "button_equal";
		this.button_equal.UseUnderline = true;
		this.button_equal.Label = global::Mono.Unix.Catalog.GetString("=");
		this.fixed1.Add(this.button_equal);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button_equal]));
		w18.X = 247;
		w18.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.output = new global::Gtk.Entry();
		this.output.WidthRequest = 260;
		this.output.HeightRequest = 55;
		this.output.CanFocus = true;
		this.output.Name = "output";
		this.output.Text = global::Mono.Unix.Catalog.GetString("0");
		this.output.IsEditable = false;
		this.output.InvisibleChar = '5';
		this.output.Xalign = 1F;
		this.fixed1.Add(this.output);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.output]));
		w19.X = 25;
		w19.Y = 79;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 303;
		this.DefaultHeight = 411;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button10.Clicked += new global::System.EventHandler(this.button_click);
		this.button1.Clicked += new global::System.EventHandler(this.button_click);
		this.button2.Clicked += new global::System.EventHandler(this.button_click);
		this.button3.Clicked += new global::System.EventHandler(this.button_click);
		this.button4.Clicked += new global::System.EventHandler(this.button_click);
		this.button5.Clicked += new global::System.EventHandler(this.button_click);
		this.button_point.Clicked += new global::System.EventHandler(this.button_click);
		this.button9.Clicked += new global::System.EventHandler(this.button_click);
		this.button6.Clicked += new global::System.EventHandler(this.button_click);
		this.button8.Clicked += new global::System.EventHandler(this.button_click);
		this.button7.Clicked += new global::System.EventHandler(this.button_click);
	}
}
